version: '3'

networks:
  compose_network: {}

services:

  mongodb:
    image: mongo:8.0.0-rc13-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - ~/docker/volumes/mongo-8.0.0/data/db/:/data/db
    networks:
      compose_network:
        aliases:
          - mongodb

  note-test-server:
    image: note-test-server:v1
    ports:
      - '9090:9090'
    environment:
      - REST_SERVER_PORT=9090
      - MONGO_HOST= mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=example
      - MONGO_DB=admin
    depends_on:
      - mongodb
    networks:
      compose_network:
        aliases:
          - note-test-server


